import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ContextProvider} from './ContextApi'
import AuthProvider from "@/provider/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quizzer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ContextProvider>
          {children}
          </ContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
